### ISSUE TITLE
Error downloading object: Content/Characters/Mannequin_UE4/Animations/Jog_Fwd.uasset

### ISSUE THREAD

**Issue by stanleyyan** [readyplayerme/UnrealExamples#29]
Error downloading object: Content/Characters/Mannequin_UE4/Animations/Jog_Fwd.uasset (81b4dd2): Smudge error: Error downloading Content/Characters/Mannequin_UE4/Animations/Jog_Fwd.uasset (81b4dd2a00331ba3086ce06a8673667359183399c5fb1ab924060e2c84720691): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

![无标题](https://github.com/readyplayerme/UnrealExamples/assets/4303389/64c34bb9-cdd3-470d-9c02-059e50388dca)

**Comment by stanleyyan** [comment]
solved by git lfs install && git lfs pull

**Comment by gadamyan** [comment]
Today we added more data packs, the issue should be resolved
