### ISSUE TITLE
Head rotation has hard-coded "Huff-IPhone", while rest of the animation uses default "Iphone" as subject name

### ISSUE THREAD

**Issue by tarmo888** [readyplayerme/UnrealExamples#33]
In BP_LiveLinkAnim.uasset file, Event Graph has "Huff-IPhone" as a Subject for "Evaluate Live Link Frame", while AnimGraph is using "Live Link Subject Name" variable, which has default "Iphone" that LiveLink app also uses. The result is that head rotation is broken  without editing the Event Graph when using default LiveLink app settings.
https://github.com/readyplayerme/UnrealExamples/blob/main/Content/ReadyPlayerMe/LiveLink/Animations/BP_LiveLinkAnim.uasset

Both, Event Graph and AnimGraph, should be using "Live Link Subject Name" variable. Even the README has inconsistent subject names, so I am guessing the variable was added to AnimGraph at some point, but wasn't added to Event Graph.
https://github.com/readyplayerme/UnrealExamples/blob/main/Content/ReadyPlayerMe/LiveLink/README.md

**Comment by gadamyan** [comment]
Thank you for the info.
This is the PR for the fix.
https://github.com/readyplayerme/UnrealExamples/pull/34
